# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a59e75ebcd19cb94d11241efdde2fab130f0eca96263b5c3e9b1f4c00232d66e07f967eb16e61f9c81275ded618cfb0348c651b33f494a6769c67a0ac0b66dab

test:
  secret_key_base: dc8121240673bb63117466b5d7e7c410632b7d35c70f0cd00dee57cb810fa211c1bb99aaf50ac69c5222573988e34c9b0caaac923fb495e165553fc8d1fb9076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
